### ISSUE TITLE
Are exported vars mutable? 

### ISSUE THREAD

**Issue by iwillig** [google/traceur-compiler#1640]
After reading the [spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-exports) I am still not sure. I just asked because I noticed that traceur uses Object.defineProperties for modules, but only defines getters. As a result when you access vars from another module they are in effect immutable. 

Sorry for noise. 

Thanks.

**Comment by arv** [comment]
The module instance object only has getters. This part is not in ES6 since ES6 does not provide a way to get a module instance objects. But previous spec drafts of the module API covered this.

Imported bindings are read only. The module that exports the binding might change the value. See http://people.mozilla.org/~jorendorff/es6-draft.html#sec-createimportbinding which is used in step 8 of http://people.mozilla.org/~jorendorff/es6-draft.html#sec-moduledeclarationinstantiation.

**Comment by iwillig** [comment]
Thanks!
