### ISSUE TITLE
Transpilation problem with a global, shadowed let, a for-of loop and an arrow function in conjunction

### ISSUE THREAD

**Issue by mnieper** [google/traceur-compiler#1671]
Compiling the program

```javascript
let c;

function f(c) {
  var p;
  for (p of g(() => c));
}
```

yields a

    RangeError: Maximum call stack size exceeded.

The error does not occur if `c` is not declared at the global level or if the argument of `f` does not shadow it. If `let` is substituted by `var` on the global level, the error also does not occur. Nor does it occur if I leave out the `for` construct so that only `g(() => c)` remains. Leaving out `g` still produces the error.

**Comment by arv** [comment]
I haven't looked into this but the bug is in the transformer.

**Comment by johnjbarton** [comment]
Here is the infinite trace:
```
transformLoop_ (traceur.js:17552)
transformForStatement (traceur.js:17598)
transform (traceur.js:7726)
transformAny (traceur.js:14130)
transformList (traceur.js:14137)
transformAnonBlock (traceur.js:14169)
transform (traceur.js:7002)
transformAny (traceur.js:14130)
transformLoop_ (traceur.js:17580)
transformForStatement (traceur.js:17598)
transform (traceur.js:7726)
transformAny (traceur.js:14130)
transformList (traceur.js:14137)
transformAnonBlock (traceur.js:14169)
transform (traceur.js:7002)
transformAny (traceur.js:14130)
transformLoop_ (traceur.js:17580)
transformForStatement (traceur.js:17598)
transform (traceur.js:7726)
transformAny (traceur.js:14130)
transformList (traceur.js:14137)
transformAnonBlock (traceur.js:14169)
transform (traceur.js:7002)
transformAny (traceur.js:14130)
transformLoop_ (traceur.js:17580)
transformForStatement (traceur.js:17598)
transform (traceur.js:7726)
transformAny (traceur.js:14130)
transformList (traceur.js:14137)
transformAnonBlock (traceur.js:14169)
transform (traceur.js:7002)
transformAny (traceur.js:14130)
transformLoop_ (traceur.js:17580)
transformForStatement (traceur.js:17598)
transform (traceur.js:7726)
transformAny (traceur.js:14130)
transformList (traceur.js:14137)
transformAnonBlock (traceur.js:14169)
transform (traceur.js:7002)
transformAny (traceur.js:14130)
transformLoop_ (traceur.js:17580)
```

**Comment by johnjbarton** [comment]
At least intuitively, the argument `c` should hide the outer scope `let c;` If so then we have a bug in the BlockBindingTransformer.

As we are processing the for-of in BlockBindingTransformer we end up in the scope of the function `f` looking for the identifier `c`.  I believe we are trying to determine if it `hasLexicalBindingName`; if not we climb to the next outer scope. I guess we also need to ask if the `identifierToken` (`c` here) `hasVaribleBindingName` and return false rather than climb.  That would express the hiding of the outer lexical binding by the argument declaration.
https://github.com/google/traceur-compiler/blob/master/src/codegeneration/BlockBindingTransformer.js#L765
```js
          while (fnScope = fnScope.parent) {
            if (fnScope.hasLexicalBindingName(identifierToken)) {
              return true;
            }
            if (fnScope === this.topScope_) break;
          }
          return false;
```
