### ISSUE TITLE
Backslash in Template Strings

### ISSUE THREAD

**Issue by tandyjames** [google/traceur-compiler#1716]
I posted an issue to the TypeScript project about a backslash (`\`) in a template string (like this: `has a \ slash`). https://github.com/Microsoft/TypeScript/issues/1984
Traceur ignores \ as a special character, where TypeScript uses it as an escape character (you need to type \\ to include a \ in the final string).
Their response to my bug ticket is that the [draft spec](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-template-literal-lexical-components) says it's supposed to be an escape character.

* The TV of TemplateCharacter :: SourceCharacter but not one of ` or \ or $ or LineTerminator is the UTF-16Encoding (10.1.1) of the code point value of SourceCharacter.
* The TV of TemplateCharacter :: \ EscapeSequence is the SV of EscapeSequence.
* The TV of LineContinuation :: \ LineTerminatorSequence is the empty code unit sequence.

And in fact, if you download Firefox Developer Edition, you can try it out and you'll get a syntax error if you try out the string `\`.

**Comment by arv** [comment]
I'm having a hard time reading your message due to how GitHub handles back ticks.

> Traceur ignores \ as a special character, 

You are incorrect. Traceur handles \ correctly according to the spec.

If you think there is a bug (other than ``` `\` ``` which I know we are handling correctly) feel free to reopen the bug.

If you add another example, please preview the message before sending to make sure it is readable.
