### ISSUE TITLE
Pass options to WebPageTranscoder

### ISSUE THREAD

**Issue by mohanr** [google/traceur-compiler#1893]
Uncaught SyntaxError: Unexpected reserved word
index.html:45 Uncaught TypeError: Cannot set property 'experimental' of undefined
traceur.js.map:1 GET http://localhost:63342/es6moduleloader/app/traceur.js.map 404 (Not Found)

I am following https://github.com/sravikiran/Angular-ES6-BookShelf/blob/master/Index.html

**Comment by arv** [comment]
We removed `traceur.options` but we didn't finish the transition. For now you can do:

```js
$traceurRuntime.options.experimental = true;
new traceur.WebPageTranscoder(document.location.href).run();
```

We should really make the following work though:

```js
new traceur.WebPageTranscoder(document.location.href, {experimental: true}).run();
```

**Comment by arv** [comment]
@johnjbarton

**Comment by khullah** [comment]
I know this is old, but the problem occurs inside the library itself, both in `traceur.js` and `BrowserSystem.js`. Also, there should be a way of passing through script tag, just as you do with `type="modules"`

**Comment by arv** [comment]
@khullah I agree. Can you create a PR?

**Comment by khullah** [comment]
Don't know if I have the skills! Anyway, it seems some things are in the right path, maybe there's not much to it:

WebPageTranscoder.js
```
... (line 48)
  addFileFromScriptElement(scriptElement, name, content) {
    let options = this.traceurOptions_;
    let elementOptionString = scriptElement.getAttribute('traceurOptions');
    if (elementOptionString) {
      options = CommandOptions.fromString(elementOptionString);
    }
```

So it seems to me that its already loading options from attributes, I just didn't know which it was. (Though it seems to not being set)

As for the other problem, I've changed one line and it seemed to work. Check if this is right.

BrowserSystem.js
```
... (line 4779)
  var CommandOptions = $traceurRuntime.getModule($traceurRuntime.normalizeModuleName("./Options.js", "traceur@0.0.112/src/WebPageTranscoder.js")).CommandOptions;
... (line 4785)
      var traceurOptions = arguments[1] !== (void 0) ? arguments[1] : new Options();
```

This of course comes from WebPageTranscoder.js lines 18 and 25, before the build. Changing it to this solved apparently:

```
      var traceurOptions = arguments[1] !== (void 0) ? arguments[1] : new CommandOptions();
```

Options doesn't exists, since it was loaded as `CommandOptions`
