### ISSUE TITLE
ReferenceError: webLoader is not defined

### ISSUE THREAD

**Issue by pYr0x** [google/traceur-compiler#1947]
i tried to test traceur at the first time with a simple example from 
https://github.com/google/traceur-compiler/wiki/LanguageFeatures#modules

my index.html looks like:
```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="https://google.github.io/traceur-compiler/bin/traceur.js"></script>
    <script src="https://google.github.io/traceur-compiler/src/bootstrap.js"></script>
</head>
<body>
<script type="module" src="app.js"></script>
</body>
</html>
```
my app.js like:
```
import {square} from 'components/test/hello-world.js'
console.log(square(2));
```
and my hello-world.js looks like:
```
export function square(x){
    return x*x;
}
```
it is very similar to the module wiki.

i got the same error as this closed issue https://github.com/google/traceur-compiler/issues/1898

what is wrong?

**Comment by johnjbarton** [comment]
There is a bug when we scan script tags that are not inline.  I have a fix.

**Comment by creamidea** [comment]
I have met the same problem. And my solution is to delete the prototype of type. Like this:
```js
<script type="module" src="app.js"></script>
```
change to 
```js
<script src="app.js"></script>
```

It works! Great. I hope this can help you :)

(PS: Is this a bug?)

**Comment by johnjbarton** [comment]
Without the `type="module"` attribute, the script tag will simply load and execute the file referenced by `src=`.  If the file is ES5 code, either natively or because it is the output of traceur applied to es6 code, that will work fine. It will also work if the browser already implements whatever es6 the file happens to use.  If the file contains es6 code that the browser does not understand, then the script tag will fail with an error.

**Comment by creamidea** [comment]
I see. Thx~
