### ISSUE TITLE
Code generation __moduleName

### ISSUE THREAD

**Issue by tbragaf** [google/traceur-compiler#2076]
Hi all!

If I use __moduleName in my code, it is being parsed to "$__moduleContext.id".
Source: https://github.com/google/traceur-compiler/blob/master/src/codegeneration/InstantiateModuleTransformer.js#L138

"__moduleName" is being parsed to "$__moduleContext.id" and "$__moduleContext" evaluates to the __moduleName itself (which is a string), so "$__moduleContext.id" evaluates to undefined.

Best regards,
tbragaf

**Comment by arv** [comment]
@tbragaf Are you saying you do not want `__moduleName` to be transformed?

This is by design when using `--modules=instantiate`. as you can see here: http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--modules%3Dinstantiate%0A%0A__moduleName

@guybedford @johnjbarton 

@guybedford

**Comment by johnjbarton** [comment]
An example that fails would be helpful here.  

I guess you mean "`$__moduleContext` evaluates to the  modules name, a string.", that is a bug if so.

**Comment by tbragaf** [comment]
Closing for this was fixed in the latest build.

**Comment by tbragaf** [comment]
@johnjbarton That was that :)

**Comment by arv** [comment]
:smiley:
