### ISSUE TITLE
Proper tail calls

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#218]
_Original author: dome...@domenicdenicola.com (March 04, 2013 06:24:43)_

The following gives a &quot;too much recursion&quot; error:

function sumTo(n, accumulator = 0) {
  return n === 0 ? accumulator : sumTo(n - 1, accumulator);
}
sumTo(123456);

_Original issue: http://code.google.com/p/traceur-compiler/issues/detail?id=215_

**Comment by mnieper** [comment]
Traceur has a CPS transformer. Together with a trampoline, proper tail calls do not seem out of reach.

However, this will slow down execution by some factor. Nevertheless, I think it is important because proper tail calls will probably the feature of ES6 that is implemented last in browser engines.

**Comment by aaronfrost** [comment]
You all are wizards. PTC always seemed like something that just wasn't possible to polyfill. I am interested to read how it happens here.

**Comment by mnieper** [comment]
Not impossible, but hard to emulate because it needs a global transformation of the program.

**Comment by arv** [comment]
Or at least manually handling all function calls.

**Comment by mnieper** [comment]
The PTC pass could be the very first pass. Every call in tail position (including setters and getters) as in

    function f() {
        k();
        return b ? g(x) : h(y);
    }

is transformed into

    function f() {
        k();
        return b ? $cont(g, x) : $cont(h, y);
    }

where

    $cont = (g, ...args) => [CONT_SENTINEL, g, ...args]

and CONT_SENTINEL is a non-forgeable, unique key.

When the final output is generated every call (including setters and getters) as in

    f(x)

is then transformed into something like

    $call(f, x)

where (again in ES6 syntax)

    $calll = (f, ...args) => {
        var c, s;
        while ((c = f(...args))[0] === CONT_SENTINEL) {
            [s, f, ...args] = c;
        }
        return c;
    }

**Comment by mnieper** [comment]
Started work along these ideas here: https://github.com/mnieper/traceur-compiler/tree/proper-tail-calls

Feel free to post suggestions.

**Comment by mnieper** [comment]
The code in the branch above now handles general tail calls properly and allows interfacing with code that does not know about this transpilation. The flag is `--proper-tail-calls`.

It's not yet finished, though, as not all expression types in possible tail position are handled yet (due to lack of time today).

@arv: As Function.prototype.call and Function.prototype.apply in tail position are not allowed to grow the stack, I have to patch them in the runtime. Is there a way for the runtime to detect whether it needs to support a particular compilation switch or not?

**Comment by arv** [comment]
> Is there a way for the runtime to detect whether it needs to support a particular compilation switch or not?

That is a slippery slope. We are trying to remove the need of doing that. One way to get around that is to inject an init call at the top of the program.

**Comment by mnieper** [comment]
Another question: Can I add a file to the runtime that is not being transpiled during the build process? My bootstrap machinery for proper tail calls cannot be compiled with the option enabled.

**Comment by johnjbarton** [comment]
Can you give a bit more context? Code that cannot be compiled by traceur but can be compiled by node seems odd.

**Comment by mnieper** [comment]
My PTC transformer (when enabled) transforms every function that has at least one tail recursive return. The transformation needs a bit of runtime. When I compile traceur with PTC enabled, it tries to transform the runtime functions it needs for the transform.

I can manually remove all tail calls from the function in my runtime part so that they are not transformed, but isn't there a better way to disable transformations for bootstrap scripts?
